language: java
jdk: openjdk8

branches:
  only:
  - master

before_install:
  - openssl aes-256-cbc -K $encrypted_0a0919813b74_key -iv $encrypted_0a0919813b74_iv -in github_deploy_key.enc -out "$HOME/.ssh/github_deploy_key" -d
  - chmod go-rwx "$HOME/.ssh/github_deploy_key"
  - eval `ssh-agent -s`
  - ssh-add "$HOME/.ssh/github_deploy_key"
  - git config --global user.name "Deployment Bot (from Travis CI)"
  - git config --global user.email "deploy@travis-ci.org"

install: ant download-libs

script: make handout/ test

after_success:
  - DIR="`mktemp -d`"
  - cd "$DIR"
  - git init
  - cp -r "$TRAVIS_BUILD_DIR/handout/." ./
  - git add ./
  - git commit -m "Committing built handout"
  - git remote add origin "git@github.com:$TRAVIS_REPO_SLUG.git"
  - git push -f origin master:handout
